markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Utbygning
url: http://kragskogen.github.io
description: Utbygning mot Holmenkollveien
twitter: olecr
github: oc
gravatar_url: http://gravatar.com/avatar/5481411a52561dcc2082b37ca788bdb9
